[package]
name = "methodify"
version = "0.1.0"
edition = "2021"
description = "Proc macro attribute that turns a function into a trait method for its first argument"
license = "MIT OR Apache-2.0"
repository = "https://github.com/smoelius/methodify"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
snapbox = "1.2.1"
